imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    sonata.user.admin.user.class: Elephant\UserBundle\Admin\UserAdmin
    sonata.user.admin.user.entity: Elephant\UserBundle\Entity\User

services:
    sonata.user.admin.group:
        abstract: true
        public: false
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ElephantAlbumBundle, ElephantWebsiteBundle, HWIOAuthBundle, FOSCommentBundle ]
    #java: /usr/bin/java
    filters:
        less:
            node: /usr/bin/nodejs
            node_paths: [/usr/local/lib/node_modules]
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secure_area
    user_class: Elephant\UserBundle\Entity\User
    registration:
        confirmation:
            enabled:    false # change to true for required email confirmation
    group:
        group_class:   Sonata\UserBundle\Entity\BaseGroup
        group_manager: sonata.user.orm.group_manager


sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_admin:
    title:      Elephant Admin

sonata_user:
    security_acl:           false

hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: secure_area
    connect: 
        confirmation: true
        account_connector: elephant.user.provider.fosub_bridge
        #registration_form_handler: hwi_oauth.registration.form.handler.fosub_bridge
        #registration_form: fos_user.registration.form

    resource_owners:
        #github:
            #type:                github
            #client_id:           <client_id>
            #client_secret:       <client_secret>
            #scope:               "user:email"
         #twitter:
            #type:                twitter
            #client_id:           <client_id>
            #client_secret:       <client_secret>   
        #facebook:
            #type:                facebook
            #client_id:           <client_id>
            #client_secret:       <client_secret>
            #options:
                #display: popup
        google:
            type:                google
            client_id:           "%google_app_id%"
            client_secret:       "%google_app_secret%"
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"

    fosub:
        # try 30 times to check if a username is available (foo, foo1, foo2 etc)
        username_iterations: 30

        # mapping between resource owners (see below) and properties
        properties:
            #github: githubID
            #twitter: twitterID
            #facebook: facebookID
            google: googleID

mopa_bootstrap:
    form: true

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Elephant\CommentBundle\Entity\Comment
            thread: Elephant\CommentBundle\Entity\Thread
