album:
    resource: "@ElephantAlbumBundle/Controller/AlbumController.php"
    type:     annotation

photo:
    resource: "@ElephantAlbumBundle/Controller/PhotoController.php"
    type:     annotation