my_album:
    resource: "@ElephantAlbumBundle/Controller/MyAlbumController.php"
    type:     annotation

album:
    resource: "@ElephantAlbumBundle/Controller/AlbumController.php"
    type:     annotation

photo:
    resource: "@ElephantAlbumBundle/Controller/PhotoController.php"
    type:     annotation

shared_album:
    resource: "@ElephantAlbumBundle/Controller/SharedAlbumController.php"
    type:     annotation